version: 3

dotenv:
  - .env

vars:
  DURATION: 60s
  RATE: 100
  ROUTER_TAG: v1.30.1

includes:
  static:
    taskfile: ./Taskfile.Test.yml
    vars:
      TEST_NAME: static-subgraph
  guid:
    taskfile: ./Taskfile.Test.yml
    vars:
      TEST_NAME: guid-response
  ca:
    taskfile: ./Taskfile.Test.yml
    vars:
      TEST_NAME: jwt-client-awareness
  shared:
    taskfile: ./Taskfile.Shared.yml

tasks:
  generate-report:
    dir: results-generator/
    cmds:
      - npm i
      - node index.js > results.md
  static:
    cmds:
      - task: shared:create-network
      - defer:
          task: shared:remove-network
      - task: shared:start-subgraphs
      - defer:
          task: shared:cleanup-subgraphs
      - task: static:baseline
      - task: static:rust
      - task: static:go
      - task: static:node
      - task: static:csharp
      - task: static:java
      - task: static:python
      - task: static:rhai
      - task: static:config

  guid:
    cmds:
      - task: shared:create-network
      - defer:
          task: shared:remove-network
      - task: shared:start-subgraphs
      - defer:
          task: shared:cleanup-subgraphs
      - task: guid:baseline
      - task: guid:rust
      - task: guid:go
      - task: guid:node
      - task: guid:csharp
      - task: guid:java
      - task: guid:python
      - task: guid:rhai

  awareness:
    cmds:
      - task: shared:create-network
      - defer:
          task: shared:remove-network
      - task: shared:start-subgraphs
      - defer:
          task: shared:cleanup-subgraphs
      - task: ca:baseline
      - task: ca:rust
      - task: ca:go
      - task: ca:node
      - task: ca:csharp
      - task: ca:java
      - task: ca:python
      - task: ca:rhai

  test-all:
    aliases:
      - all
      - test
    cmds:
      - task: static
      - task: guid
      - task: awareness
      - task: generate-report
