version: 3

dotenv:
  - .env

vars:
  COPROCESSOR_PORT: 8000
  DURATION: 30s
  RATE: 100
  ROUTER_TAG: v1.19.0

includes:
  static:
    taskfile: ./Taskfile.Test.yml
    vars:
      TEST_NAME: static-subgraph
  guid:
    taskfile: ./Taskfile.Test.yml
    vars:
      TEST_NAME: guid-response
  ca:
    taskfile: ./Taskfile.Test.yml
    vars:
      TEST_NAME: jwt-client-awareness
  local:
    taskfile: ./Taskfile.Test.yml
    vars:
      TEST_NAME: local-subgraphs
  shared:
    taskfile: ./Taskfile.Shared.yml

tasks:
  generate-report:
    dir: results-generator/
    cmds:
      - npm i
      - node index.js > results.md
  static:
    cmds:
      - task: static:setup-subgraphs
      - task: static:baseline
      - task: static:go
      - task: static:node
      - task: static:csharp
      - task: static:java
      - task: static:python
      - task: static:rhai
      - task: static:config
      - task: static:cleanup-subgraphs

  guid:
    cmds:
      - task: guid:setup-subgraphs
      - task: guid:baseline
      - task: guid:go
      - task: guid:node
      - task: guid:csharp
      - task: guid:java
      - task: guid:python
      - task: guid:rhai
      - task: guid:cleanup-subgraphs

  awareness:
    cmds:
      - task: ca:setup-subgraphs
      - task: ca:baseline
      - task: ca:go
      - task: ca:node
      - task: ca:csharp
      - task: ca:java
      - task: ca:python
      - task: ca:cleanup-subgraphs

  test-local:
    aliases:
      - local
    cmds:
      - task: local:setup-subgraphs
      - task: local:baseline
      - task: local:local-subgraphs
      - task: local:cleanup-subgraphs
      - task: generate-report
  
  test-all:
    aliases:
      - all
      - test
    cmds:
      - task: static
      - task: guid
      - task: awareness
      - task: generate-report
