version: 3

dotenv:
  - .env

vars:
  COPROCESSOR_PORT: 8000
  DURATION: 30s
  RATE: 100

includes:
  static:
    taskfile: ./Taskfile.Test.yml
    vars:
      TEST_NAME: static-subgraph
  guid:
    taskfile: ./Taskfile.Test.yml
    vars:
      TEST_NAME: guid-response
  ca:
    taskfile: ./Taskfile.Test.yml
    vars:
      TEST_NAME: jwt-client-awareness
  shared:
    taskfile: ./Taskfile.Shared.yml

tasks:
  generate-report:
    dir: results-generator/
    cmds:
      - npm i
      - node index.js > results.md
  static:
    cmds:
      - task: static:baseline
      - task: static:go
      - task: static:node
      - task: static:csharp
      - task: static:rhai
      - task: static:config
  guid:
    cmds:
      - task: guid:baseline
      - task: guid:go
      - task: guid:node
      - task: guid:csharp
      - task: guid:rhai
  awareness:
    cmds:
      - task: ca:baseline
      - task: ca:go
      - task: ca:node
      - task: ca:csharp
  test-all:
    aliases:
      - all
      - test
    cmds:
      - task: static
      - task: guid
      - task: awareness
      - task: generate-report
