name: Update benchmarks
on:
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Generate report
        run: task test-all
      - name: Save report
        uses: actions/upload-artifact@v3
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
          APOLLO_GRAPH_REF: ${{ secrets.APOLLO_GRAPH_REF }}
        with:
          name: results
          path: results-generator/results.md